ALTER TABLE "TenantConfig" ADD COLUMN "bgType" TEXT NOT NULL DEFAULT 'solid';
ALTER TABLE "TenantConfig" ADD COLUMN "bgImageUrl" TEXT;
ALTER TABLE "TenantConfig" ADD COLUMN "bgGradientFrom" TEXT NOT NULL DEFAULT '#FDE5C3';
ALTER TABLE "TenantConfig" ADD COLUMN "bgGradientTo" TEXT NOT NULL DEFAULT '#FFF6E9';
ALTER TABLE "TenantConfig" ADD COLUMN "bgGradientAngle" INTEGER NOT NULL DEFAULT 135;
ALTER TABLE "TenantConfig" ADD COLUMN "logoFullscreen" INTEGER NOT NULL DEFAULT 0;
