// @ts-expect-error - NODE_ENV is read-only, but we need to set it for tests
process.env.NODE_ENV = process.env.NODE_ENV || 'test'
process.env.UPSTASH_REDIS_REST_URL = process.env.UPSTASH_REDIS_REST_URL || 'https://example.com'
process.env.UPSTASH_REDIS_REST_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN || 'token'
process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY || ''
process.env.TURNSTILE_SECRET_KEY = process.env.TURNSTILE_SECRET_KEY || ''
process.env.TURNSTILE_SECRET = process.env.TURNSTILE_SECRET || ''
process.env.SENTRY_DSN = process.env.SENTRY_DSN || ''
process.env.LOG_LEVEL = process.env.LOG_LEVEL || 'silent'
process.env.AUTH_SECRET = process.env.AUTH_SECRET || 'test-auth-secret-placeholder'